### ISSUE TITLE
Testing POST.Dose

### ISSUE THREAD

**Issue by eak24** [AguaClara/post.dose#11]
Hi @asm278 I just downloaded and built the latest post.dose on the master branch (which looks like the most up to date) with commit 9ae96ae091c2c43baacc8ba08c129ac2a7261e1c and when I open it from the POST.collect app with the test form you defined in this repo, I get the following error from the android monitor: 

`12-02 13:46:35.523 32258-32258/org.post.aguaclara.postdose E/AndroidRuntime: FATAL EXCEPTION: main
                                                                             Process: org.post.aguaclara.postdose, PID: 32258
                                                                             java.lang.RuntimeException: Unable to start activity ComponentInfo{org.post.aguaclara.postdose/org.post.aguaclara.postdose.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3254)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
                                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:222)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:158)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7229)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                              Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Object.toString()' on a null object reference
                                                                                 at org.post.aguaclara.postdose.MainActivity.onCreate(MainActivity.java:93)
                                                                                 at android.app.Activity.performCreate(Activity.java:6876)
                                                                                 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
                                                                                 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
                                                                                 at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                 at android.os.Looper.loop(Looper.java:158) 
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:7229) 
                                                                                 at java.lang.reflect.Method.invoke(Native Method)`

Note that the form did not ask me for the raw water turbidity before it had the "launch suggested coagulant dose" button. 

Replication steps are:
- download post.collect from playstore
- run post.dose from android studio
- download the TEST POST Dose 1 form I uploaded to the dev server (same xml as you defined for a test form)
- run the form and hit "launch" on the third q. 
- the app should post a toast error message and the NPE should show up in the android monitor in Android Studio. 

Sorry I can't dig into this more, but once you get it running, bump me here and I will try again!

**Comment by asm278** [comment]
Whoops, I forgot that there was a form in this repo. 

I branched [odkforms](https://github.com/AguaClara/post.odkForms/commit/3bcf660e8c9e1567f8cefc30c439427a013521e7) with a form that should work with the app.

**Comment by eak24** [comment]
@asm278 this looks great so far. Just a few comments/questions:
- When there is no model pulled from the server, the recommender produces a -1... It's not clear that this is an error code. Is there anyway to have ODK present an error from the activity's result without much effort? (without modifying the ODK source code...) if not, perhaps we should include a message in the hint about what -1 means. 
- The recommendation was too specific... 5.067 should be 5. Or perhaps even 4-6. I think giving a range might even be a bit more friendly. Thoughts on that?
- Is there any way to record what the recommendation was so that we can evaluate compliancy? 
- Is there any way to make it so the user doesn't have to click the launch button? I'm thinking ODK might be able to launch the dose activity as soon as you 'flip the page'... is that possible (small thing not worth much effort.) 

That's it for now. See you tomorrow AM!
